[enb]
mcc = 421
mnc = 01
n_prb = 50
earfcn = 3350
pci = 1
tac = 100
cell_id = 0x01

[rf]
device_name = zmq
device_args = fail_on_create=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001

[sib]
tac = 100
cell_id = 0x01
